### ISSUE TITLE
When I create a PR for iOS code, I cannot assign a reviewer.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2023#1186]
**Describe the bug**
- The title says it all.

**To Reproduce**
1. Code to change only the iOS side code (Swift file) as PR
2. No reviewers are assigned when a PR is created.

**Expected behavior**
Reviewers will be assigned appropriately, just as they would be if the Android side of the code were changed.

**Link**
https://github.com/DroidKaigi/conference-app-2023/blob/main/.github/CODEOWNERS#L2

**Comment by tkhs0604** [comment]
@Corvus400 
Hmm... For example, a reviewer group for iOS side seems to be add automatically in https://github.com/DroidKaigi/conference-app-2023/pull/1193... 🤔
This group looks recognized as a codeowner properly.
![image](https://github.com/DroidKaigi/conference-app-2023/assets/43767445/425ac0fb-9443-43b8-8f79-8b5c373c178e)

**Comment by Corvus400** [comment]
@tkhs0604 
No one seems to be assigned on my end. 🤔 
Perhaps other iOS PRs I have created have been assigned that AppiOS? 👻 
<img width="1269" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/13657682/10cff3ea-7e11-477d-9a8b-cd84494584a9">

**Comment by tkhs0604** [comment]
Ah, it's because the above PR is still draft. If I open the PR once, iOS team will be assigned as a reviewer 👀
![image](https://github.com/DroidKaigi/conference-app-2023/assets/43767445/963d4ec0-f8de-44c7-8e45-2d0c4002a69d)

> Perhaps other iOS PRs I have created have been assigned that AppiOS? 👻

To be honest, I am not sure what happens to your local 🙏 But if this is not your manual operation, the answer must be yes 👍 
Ex: https://github.com/DroidKaigi/conference-app-2023/pull/1178
![image](https://github.com/DroidKaigi/conference-app-2023/assets/43767445/9c490475-ae03-4180-8d91-3fce57d4c3f2)

**Comment by tarumzu** [comment]
@tkhs0604 cc @Corvus400 I see. We just can't see it because your team visibility is Secret.
As shown below, You are in "a team" so We cannot see your assignment.
<img width="565" alt="Screen Shot 2023-09-12 at 23 42 25" src="https://github.com/DroidKaigi/conference-app-2023/assets/9943053/05584d34-9826-4d37-9a34-d865c2bd478e">

**Comment by tkhs0604** [comment]
@tarumzu 
Thank you for your further investigation!
The AppiOS team must be visible ([here](https://github.com/orgs/DroidKaigi/teams/appios)), but "Enable auto assignment" might not be applied to this team 🤔
In fact, I don't have access to this settings, so let me take this topic back to admin members 🙏

**Comment by tkhs0604** [comment]
Thank you both! I learned a lot from your comments! Then, let me close this issue at this time 🙏
I hope we can improve the PR review flow next time 💪
