### ISSUE TITLE
Improve collapsing animation on timetable item detail screen

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#372]
## What we want
When the timetable item detail screen is scrolled quite slowly, the text in the app bar behaves a little weirdly ([movie](https://github.com/DroidKaigi/conference-app-2023/assets/43767445/c4754dca-5e35-4031-a388-9619d3f5345b)).
I would like to refine this behavior more smoothly.

The following is what I care.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/51fdbdda-e624-4edf-9503-b2028bd727ce" width="300">

## Related
https://github.com/DroidKaigi/conference-app-2023/pull/365#issuecomment-1667398106

**Comment by Corvus400** [comment]
@tkhs0604 
I would appreciate it if you could check the video link as I can't seem to access it! 🙏
![image](https://github.com/DroidKaigi/conference-app-2023/assets/13657682/caa147fb-d5c1-4b4a-830b-6d58272f4d5b)

**Comment by tkhs0604** [comment]
@Corvus400 
My bad, updated it 🙏 Could you please double check if you can access to the movie file again? 
By the way, this issue might be influenced by https://github.com/DroidKaigi/conference-app-2023/issues/464 👀

**Comment by tepi0820** [comment]
Is it alright if I take a try on this issue?

I am thinking to fix this by 

* Make a `Box` with `Text` and `ResizeableText` 
* Animate alpha of the `Text` and `ResizeableText` using `scrollBehavior.state.collapsedFraction` to hide and show the composables

so the fix can hide the point where the `isCollapsed` changes which, I think, is making the weird behavior.

I already have the fix on my local and it works like this.

https://github.com/DroidKaigi/conference-app-2023/assets/11084143/ee1dde91-bfeb-4547-878c-0bd7db0b09d4

Let me know if this is good enough for the fix and assign me this issue if there are no problems.

※Please do not hesitate to say the fix is not good. I am really fine with it!
※This is my first contribution to OSS, so let me know if I am making mistakes.

**Comment by tkhs0604** [comment]
@tepi0820 
Thank you for your investigation and implementation! Looks much better than now for me ✨
It would be appreciated if you could make a PR for that 🙏

**Comment by tepi0820** [comment]
@tkhs0604 
Thank you for your comment!

It still needs some more tunings since it is not working well depending on the title length, so let me have some time to work on it and I will make a PR as soon as I finished fixing.

**Comment by tkhs0604** [comment]
@tepi0820 
Thank you for letting us know the current status, that's no problem at all 👍

**Comment by tepi0820** [comment]
@tkhs0604 
I have created a PR as above! I was not so sure about how to create a PR, so please let me know if I was doing something wrong.
