### ISSUE TITLE
Change the Number of Tags Displayed in Search Screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2023#839]
**Idea Description**
Adjust the number of tags displayed in the search screen as per the requirements or design guidelines.

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?node-id=54462%3A36316&mode=dev
<img width="352" alt="image" src="https://github.com/DroidKaigi/conference-app-2023/assets/1386930/7d485255-7042-48ed-80fe-9f3e0cfbd2ac">

**Comment by kkkkan** [comment]
Hello,

I apologize for reaching out while you're likely busy. 
The issue here is labeled as "blocked." Would it be possible to address this and submit a pull request?
 I'm interested in contributing if it's acceptable. However, I'm unsure about the meaning of the "blocked" label, and I'm uncertain whether it's appropriate to proceed with a pull request similar to those labeled "welcome contribute" This uncertainty has left me wondering how to proceed.

Thank you for your guidance and consideration.

Best regards,

**Comment by takahirom** [comment]
@kkkkan I'm not sure why this is blocked 😭 Thanks! I assigned!

**Comment by kkkkan** [comment]
Thanks for the reply!

Thank you again for the assignment!🙋
