### ISSUE TITLE
[iOS] Fix 対応言語 part to be displayed in the user's current language

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#875]
## Summary
対応言語 is displayed as JAPANESE even if the user's locale setting is Japanese.
<img src="https://github.com/DroidKaigi/conference-app-2023/assets/43767445/85afcf4d-8939-4ec1-b4f8-96a04d9c1118" width="300">

**Comment by fumiyasac** [comment]
@tkhs0604 
If you write down the ideal state after correction, I think that the part you want to fix will be clearly communicated.
(For example, Please teach state "As is" & "To be"🙏 )
Thanks.

**Comment by ry-itto** [comment]
@fumiyasac 
Thank you for your advice!

Current "対応言語" isn't correct. So iOS App should use following method result instead of current one.

https://github.com/DroidKaigi/conference-app-2023/blob/70064bf807325c23c3c885b7c073dbabf60c6b77/core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/model/TimetableItem.kt#L95-L109

---

As is: iOS App uses `langOfSpeaker`
To be: should use `getSupportedLangString(isJapaneseLocale: <#T##Bool#>)` instead of current one

**Comment by fumiyasac** [comment]
✋（I already pushed pull request...）

**Comment by ry-itto** [comment]
@fumiyasac 
Thanks! Assigned 👍🏼  And I'll check PR later 🙇🏼
